package com.sxu.model;

/**
 * TDoc generated by MyEclipse Persistence Tools
 */

public class TDoc implements java.io.Serializable
{

	private Integer id;
	private String sdate;
	private String edate;
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getSdate() {
		return sdate;
	}
	public void setSdate(String sdate) {
		this.sdate = sdate;
	}
	public String getEdate() {
		return edate;
	}
	public void setEdate(String edate) {
		this.edate = edate;
	}
	 
	
	 
}