package com.sxu.model;

/**
 * TStu generated by MyEclipse Persistence Tools
 */

public class TMessage implements java.io.Serializable
{

	// Fields

	private Integer id;
	private Integer tid;
	private String mdate;
	private Integer state;
	private String minfo;
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public Integer getTid() {
		return tid;
	}
	public void setTid(Integer tid) {
		this.tid = tid;
	}
	public String getMdate() {
		return mdate;
	}
	public void setMdate(String mdate) {
		this.mdate = mdate;
	}
	public Integer getState() {
		return state;
	}
	public void setState(Integer state) {
		this.state = state;
	}
	public String getMinfo() {
		return minfo;
	}
	public void setMinfo(String minfo) {
		this.minfo = minfo;
	}
    
	
	 

	

}