package com.sxu.model;

/**
 * TStu generated by MyEclipse Persistence Tools
 */

public class TStu implements java.io.Serializable
{

	// Fields

	private Integer stuId;
	private String stuXuehao;
	private String stuRealname;
	private String stuSex;

	private String stuAge;
	private String loginPw;
	private String zhuangtai;
	private String del;
	private Integer teaid=0;
	private String zhuanye;
	private String nianji;
	private String telphone;
	
	
	
	public String getZhuanye() {
		return zhuanye;
	}
	public void setZhuanye(String zhuanye) {
		this.zhuanye = zhuanye;
	}
	public String getNianji() {
		return nianji;
	}
	public void setNianji(String nianji) {
		this.nianji = nianji;
	}
	public String getTelphone() {
		return telphone;
	}
	public void setTelphone(String telphone) {
		this.telphone = telphone;
	}
	public String getDel()
	{
		return del;
	}
	public void setDel(String del)
	{
		this.del = del;
	}
	
	public String getZhuangtai()
	{
		return zhuangtai;
	}
	public void setZhuangtai(String zhuangtai)
	{
		this.zhuangtai = zhuangtai;
	}
	public String getLoginPw()
	{
		return loginPw;
	}
	public void setLoginPw(String loginPw)
	{
		this.loginPw = loginPw;
	}
	public String getStuAge()
	{
		return stuAge;
	}
	public void setStuAge(String stuAge)
	{
		this.stuAge = stuAge;
	}
	public Integer getStuId()
	{
		return stuId;
	}
	public void setStuId(Integer stuId)
	{
		this.stuId = stuId;
	}
	public String getStuRealname()
	{
		return stuRealname;
	}
	public void setStuRealname(String stuRealname)
	{
		this.stuRealname = stuRealname;
	}
	public String getStuSex()
	{
		return stuSex;
	}
	public void setStuSex(String stuSex)
	{
		this.stuSex = stuSex;
	}
	public String getStuXuehao()
	{
		return stuXuehao;
	}
	public void setStuXuehao(String stuXuehao)
	{
		this.stuXuehao = stuXuehao;
	}
	public Integer getTeaid() {
		return teaid;
	}
	public void setTeaid(Integer teaid) {
		this.teaid = teaid;
	}

	

}