//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace moocweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exampaper
    {
        public long exam_id { get; set; }
        public long paper_id { get; set; }
        public bool israndom { get; set; }
        public long admin_tea { get; set; }
        public string paper_name { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public bool isopen { get; set; }
        public int qcount { get; set; }
        public long Id { get; set; }
    }
}
