//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace moocweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class examclass
    {
        public long Id { get; set; }
        public long class_id { get; set; }
        public long exam_id { get; set; }
        public Nullable<long> tea_id { get; set; }
        public string class_name { get; set; }
        public string name { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime end_time { get; set; }
        public System.TimeSpan test_time { get; set; }
        public Nullable<long> college_id { get; set; }
        public string tea_name { get; set; }
    }
}
