//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace moocweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public paper()
        {
            this.paper_ques = new HashSet<paper_ques>();
            this.exam_paper = new HashSet<exam_paper>();
        }
    
        public long id { get; set; }
        public string paper_name { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public bool isopen { get; set; }
        public bool isdelete { get; set; }
        public Nullable<short> type { get; set; }
    
        public virtual teacher_info teacher_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<paper_ques> paper_ques { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<exam_paper> exam_paper { get; set; }
    }
}
