//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace moocweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qbaseset
    {
        public long id { get; set; }
        public string set_name { get; set; }
        public Nullable<long> admin_id { get; set; }
        public string tea_name { get; set; }
        public Nullable<int> qbase_count { get; set; }
        public bool isopen { get; set; }
        public string describe { get; set; }
    }
}
