//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace moocweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public question()
        {
            this.ques_judge = new HashSet<ques_judge>();
            this.paper_ques = new HashSet<paper_ques>();
        }
    
        public long id { get; set; }
        public Nullable<long> chap_id { get; set; }
        public Nullable<short> q_type { get; set; }
        public string title { get; set; }
        public string right_answer { get; set; }
        public string ans1 { get; set; }
        public string ans2 { get; set; }
        public string ans3 { get; set; }
        public string ans4 { get; set; }
        public string ans5 { get; set; }
        public string ans6 { get; set; }
        public Nullable<short> hard_level { get; set; }
        public string check_sentence { get; set; }
        public short totvalue { get; set; }
        public bool isdelete { get; set; }
        public string output { get; set; }
    
        public virtual qbase_chapter qbase_chapter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ques_judge> ques_judge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<paper_ques> paper_ques { get; set; }
    }
}
