//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace moocweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quesanswer
    {
        public long id { get; set; }
        public Nullable<long> chap_id { get; set; }
        public Nullable<short> q_type { get; set; }
        public string title { get; set; }
        public string right_answer { get; set; }
        public string ans1 { get; set; }
        public string ans2 { get; set; }
        public string ans3 { get; set; }
        public string ans4 { get; set; }
        public string ans5 { get; set; }
        public string ans6 { get; set; }
        public Nullable<short> hard_level { get; set; }
        public string check_sentence { get; set; }
        public string output { get; set; }
        public short totvalue { get; set; }
        public bool isdelete { get; set; }
        public string detail { get; set; }
        public string back_describe { get; set; }
        public string chap_name { get; set; }
        public long paper_id { get; set; }
        public long nowvalue { get; set; }
        public long pqid { get; set; }
    }
}
