//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace moocweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stu_exam_right_answer
    {
        public string wronginfo { get; set; }
        public Nullable<System.TimeSpan> cost { get; set; }
        public long ec_id { get; set; }
        public Nullable<decimal> score { get; set; }
        public string ans { get; set; }
        public long pq_id { get; set; }
        public long stu_id { get; set; }
        public long id { get; set; }
        public string right_answer { get; set; }
        public string title { get; set; }
        public Nullable<short> q_type { get; set; }
        public string ans1 { get; set; }
        public string ans2 { get; set; }
        public string ans3 { get; set; }
        public string ans4 { get; set; }
        public string ans5 { get; set; }
        public string ans6 { get; set; }
    }
}
