//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace moocweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stu_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public stu_info()
        {
            this.stu_class = new HashSet<stu_class>();
            this.notice_stu_class = new HashSet<notice_stu_class>();
            this.stu_ans_log = new HashSet<stu_ans_log>();
            this.stu_paperques = new HashSet<stu_paperques>();
            this.timeless = new HashSet<timeless>();
        }
    
        public string stu_num { get; set; }
        public string name { get; set; }
        public string pass { get; set; }
        public Nullable<bool> gender { get; set; }
        public string phonenum { get; set; }
        public string emailaddress { get; set; }
        public Nullable<long> college_id { get; set; }
        public string major { get; set; }
        public bool isdelete { get; set; }
        public long id { get; set; }
        public string lastIP { get; set; }
        public Nullable<System.DateTime> lastTime { get; set; }
    
        public virtual college_info college_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stu_class> stu_class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notice_stu_class> notice_stu_class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stu_ans_log> stu_ans_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stu_paperques> stu_paperques { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timeless> timeless { get; set; }
    }
}
