//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace moocweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stu_paperques
    {
        public long Id { get; set; }
        public string ans { get; set; }
        public Nullable<int> cost { get; set; }
        public Nullable<decimal> score { get; set; }
        public string wrongtype { get; set; }
        public bool state { get; set; }
    
        public virtual paper_ques paper_ques { get; set; }
        public virtual stu_info stu_info { get; set; }
    }
}
