//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace moocweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StuClass
    {
        public long id { get; set; }
        public long stu_id { get; set; }
        public Nullable<long> class_id { get; set; }
        public bool isdelete { get; set; }
        public string name { get; set; }
        public Nullable<bool> gender { get; set; }
        public string lastIP { get; set; }
        public Nullable<System.DateTime> lastTime { get; set; }
        public string stu_num { get; set; }
        public string pass { get; set; }
    }
}
