//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace moocweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stupaperques_prac
    {
        public bool type { get; set; }
        public long stu_id { get; set; }
        public long pqid { get; set; }
        public long eid { get; set; }
        public Nullable<short> q_type { get; set; }
        public string title { get; set; }
        public string right_answer { get; set; }
        public string output { get; set; }
        public string detail { get; set; }
        public Nullable<int> cost { get; set; }
        public Nullable<bool> state { get; set; }
        public string wrongtype { get; set; }
        public string stu_ans { get; set; }
    }
}
