//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace moocweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher_class
    {
        public long id { get; set; }
        public Nullable<long> tea_id { get; set; }
        public Nullable<long> class_id { get; set; }
    
        public virtual @class @class { get; set; }
        public virtual teacher_info teacher_info { get; set; }
    }
}
